import { Plant } from '../../models/Plant.js';

const plantData = [
      {
        id: '',
        common_name: 'jade plant',
        scientific_name: 'crassula ovata',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/jadePlantFinal/', 
      },
      {
        id: '',
        common_name: "burro's tail",
        scientific_name: 'sedum morganianum',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/burrosTailFinal/', 
      },
      {
        id: '',
        common_name: 'crown of thorns',
        scientific_name: 'euphorbia milii',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/crownOfThornsFinal/', 
      },
      {
        id: '',
        common_name: 'panda plant',
        scientific_name: 'kalanchoe tomentosa',
        url: '', 
      },
      {
        id: '',
        common_name: "snake plant,mother in law's tongue",
        scientific_name: 'dracaena trifasciata',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/snakePlantFinal/', 
      },
      {
        id: '',
        common_name: 'zebra cactus',
        scientific_name: 'haworthiopsis attenuata',
        url: '', 
      },
      {
        id: '',
        common_name: 'christmas cactus',
        scientific_name: 'schlumbergera',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/christmasCactusFinal/', 
      },
      {
        id: '',
        common_name: 'easter lily cactus',
        scientific_name: 'echinopsis ancistrophora',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/easterLilyCactusFinal/',  
      },
      {
        id: '',
        common_name: "elephants's foot plant",
        scientific_name: 'dioscorea elephantipes',
        url: '', 
      },
      {
        id: '',
        common_name: 'hoya hindu rope',
        scientific_name: 'carnosa compacta',
        url: '', 
      },
      {
        id: '',
        common_name: 'pencil cactus',
        scientific_name: 'euphorbia tirucalli',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/pencilCactusFinal/', 
      },
      {
        id: '',
        common_name: 'string of hearts',
        scientific_name: 'ceropegia',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/stringOfHeartsFinal/', 
      },
      {
        id: '',
        common_name: 'string of pearls',
        scientific_name: 'senecio rowleyanus',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/stringOfPearlsFinal/', 
      },
      {
        id: '',
        common_name: 'dolphin succulent',
        scientific_name: 'senecio peregrinus',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/dolphinPlantFinal/', 
      },
      {
        id: '',
        common_name: 'fishbone cactus',
        scientific_name: 'epiphyllum anguliger',
        url: '', 
      },
      {
        id: '',
        common_name: 'truncate living stone',
        scientific_name: 'lithops pseudotruncatella',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/livingStoneFinal/', 
      },
      {
        id: '',
        common_name: 'spiral cactus',
        scientific_name: "cereus forbesii 'spiralis'",
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/spiralCactusFinal/', 
      },
      {
        id: '',
        common_name: 'old lady cactus',
        scientific_name: 'mammillaria hahniana',
        url: '', 
      },
      {
        id: '',
        common_name: 'desert rose',
        scientific_name: 'adenium obesum',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/desertRoseFinal/', 
      },
      {
        id: '',
        common_name: 'rose,rosa',
        scientific_name: 'rosaceae',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/roseFinal/', 
      },
      {
        id: '',
        common_name: 'bougainvillea',
        scientific_name: 'bougainvillea glabra',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/bougainvilleaFinal/', 
      },
      {
        id: '',
        common_name: 'gardenia',
        scientific_name: 'gardenia jasminoides',
        url: '', 
      },
      {
        id: '',
        common_name: 'hibiscus',
        scientific_name: 'hibiscus rosa-sinensis',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/hibiscusFinal/', 
      },
      {
        id: '',
        common_name: 'periwinkle',
        scientific_name: 'myrtle,vinca minor',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/vincaFinal/', 
      },
      {
        id: '',
        common_name: 'rio,rock trumpet',
        scientific_name: 'diplandenia,mandevilla',
        url: '', 
      },
      {
        id: '',
        common_name: "widow's thrill",
        scientific_name: 'kalanchoe',
        url: '', 
      },
      {
        id: '',
        common_name: 'begonia',
        scientific_name: '',
        url: '', 
      },
      {
        id: '',
        common_name: 'plumeria',
        scientific_name: 'frangipani',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/plumeriaFinal/', 
      },
      {
        id: '',
        common_name: 'lotus,indian lotus,sacred lotus',
        scientific_name: 'nelumbo nucifera',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/lotusFinal/', 
      },
      {
        id: '',
        common_name: 'rattlesnake plant',
        scientific_name: 'goeppertia insignis',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/rattlesnakeFinal/', 
      },
      {
        id: '',
        common_name: 'swiss cheese plant,monstera',
        scientific_name: 'monstera deliciosa,split leaf philodendron',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/monsteraFinal/', 
      },
      {
        id: '',
        common_name: 'fiddle leaf fig',
        scientific_name: 'ficus lyrata',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/fiddleLeafFigFinal/', 
      },
      {
        id: '',
        common_name: 'lucky bamboo',
        scientific_name: 'dracaena sanderiana',
        url: '', 
      },
      {
        id: '',
        common_name: 'peace lily',
        scientific_name: 'spathiphyllum',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/peaceLilyFinal/', 
      },
      {
        id: '',
        common_name: 'ponytail palm',
        scientific_name: 'beaucarnea recurvata',
        url: '', 
      },
      {
        id: '',
        common_name: 'pothos',
        scientific_name: 'epipremnum aureum',
        url: '', 
      },
      {
        id: '',
        common_name: 'bromeliad',
        scientific_name: 'bromeliaceae',
        url: '', 
      },
      {
        id: '',
        common_name: 'orchid',
        scientific_name: 'orchidaceae',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/orchidFinal/', 
      },
      {
        id: '',
        common_name: 'english ivy',
        scientific_name: 'hedera helix',
        url: '', 
      },
      {
        id: '',
        common_name: "elephant's ear",
        scientific_name: 'alocasia',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/elephantEarsFinal/', 
      },
      {
        id: '',
        common_name: 'prayer plant',
        scientific_name: 'maranta leuconeura',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/prayerPlantFinal/', 
      },
      {
        id: '',
        common_name: 'money tree',
        scientific_name: 'pachira aquatica',
        url: '', 
      },
      {
        id: '',
        common_name: 'chinese money plant',
        scientific_name: 'pilea peperomioides',
        url: '', 
      },
      {
        id: '',
        common_name: 'madagascar palm',
        scientific_name: 'pachypodium lamerei',
        url: '', 
      },
      {
        id: '',
        common_name: 'staghorn ferns',
        scientific_name: 'platycerium',
        url: '', 
      },
      {
        id: '',
        common_name: 'zz plant',
        scientific_name: 'zamioculcas',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/zzPlantFinal/', 
      },
];

const seedPlants = () => Plant.bulkCreate(plantData)
