import { Plant } from '../../models/Plant.js';

const plantData = [
      {
        id: '',
        common_name: 'jade plant',
        scientific_name: 'crassula ovata',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/jadePlantFinal/', 
      },
      {
        id: '',
        common_name: "burro's tail",
        scientific_name: 'sedum morganianum',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/burrosTailFinal/', 
      },
      {
        id: '',
        common_name: 'crown of thorns',
        scientific_name: 'euphorbia milii',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/crownOfThornsFinal/', 
      },
      {
        id: '',
        common_name: 'panda plant',
        scientific_name: 'kalanchoe tomentosa',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/pandaPlantFinal/', 
      },
      {
        id: '',
        common_name: "snake plant,mother in law's tongue",
        scientific_name: 'dracaena trifasciata',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/snakePlantFinal/', 
      },
      {
        id: '',
        common_name: 'zebra cactus',
        scientific_name: 'haworthiopsis attenuata',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/zebraPlantFinal/', 
      },
      {
        id: '',
        common_name: 'christmas cactus',
        scientific_name: 'schlumbergera',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/christmasCactusFinal/', 
      },
      {
        id: '',
        common_name: 'easter lily cactus',
        scientific_name: 'echinopsis ancistrophora',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/easterLilyCactusFinal/',  
      },
      {
        id: '',
        common_name: "elephants's foot plant",
        scientific_name: 'dioscorea elephantipes',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/elephantsFootFinal/', 
      },
      {
        id: '',
        common_name: 'hoya hindu rope',
        scientific_name: 'carnosa compacta',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/hoyaHinduRopeFinal/', 
      },
      {
        id: '',
        common_name: 'pencil cactus',
        scientific_name: 'euphorbia tirucalli',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/pencilCactusFinal/', 
      },
      {
        id: '',
        common_name: 'string of hearts',
        scientific_name: 'ceropegia',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/stringOfHeartsFinal/', 
      },
      {
        id: '',
        common_name: 'string of pearls',
        scientific_name: 'senecio rowleyanus',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/stringOfPearlsFinal/', 
      },
      {
        id: '',
        common_name: 'dolphin succulent',
        scientific_name: 'senecio peregrinus',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/dolphinPlantFinal/', 
      },
      {
        id: '',
        common_name: 'fishbone cactus',
        scientific_name: 'epiphyllum anguliger',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/fishboneCactusFinal/', 
      },
      {
        id: '',
        common_name: 'truncate living stone',
        scientific_name: 'lithops pseudotruncatella',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/livingStoneFinal/', 
      },
      {
        id: '',
        common_name: 'spiral cactus',
        scientific_name: "cereus forbesii 'spiralis'",
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/spiralCactusFinal/', 
      },
      {
        id: '',
        common_name: 'rubber tree',
        scientific_name: 'ficus elastica',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/rubberTreeFinal/', 
      },
      {
        id: '',
        common_name: 'old lady cactus',
        scientific_name: 'mammillaria hahniana',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/oldLadyCactusFinal/', 
      },
      {
        id: '',
        common_name: 'umbrella tree',
        scientific_name: 'schefflera arboricola',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/umbrellaTreeFinal/', 
      },
      {
        id: '',
        common_name: 'desert rose',
        scientific_name: 'adenium obesum',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/desertRoseFinal/', 
      },
      {
        id: '',
        common_name: 'rose,rosa',
        scientific_name: 'rosaceae',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/roseFinal/', 
      },
      {
        id: '',
        common_name: 'bougainvillea',
        scientific_name: 'bougainvillea glabra',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/bougainvilleaFinal/', 
      },
      {
        id: '',
        common_name: 'gardenia',
        scientific_name: 'gardenia jasminoides',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/gardeniaFinal/', 
      },
      {
        id: '',
        common_name: 'hibiscus',
        scientific_name: 'hibiscus rosa-sinensis',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/hibiscusFinal/', 
      },
      {
        id: '',
        common_name: 'periwinkle',
        scientific_name: 'myrtle,vinca minor',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/vincaFinal/', 
      },
      {
        id: '',
        common_name: 'rio,rock trumpet',
        scientific_name: 'diplandenia,mandevilla',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/rioFinal/', 
      },
      {
        id: '',
        common_name: "widow's thrill",
        scientific_name: 'kalanchoe',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/widowsThrillFinal/', 
      },
      {
        id: '',
        common_name: 'wax begonia',
        scientific_name: 'begonia x semperflorens-cultorum',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/waxBegoniaFinal/', 
      },
      {
        id: '',
        common_name: 'plumeria',
        scientific_name: 'frangipani',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/plumeriaFinal/', 
      },
      {
        id: '',
        common_name: 'lotus,indian lotus,sacred lotus',
        scientific_name: 'nelumbo nucifera',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/lotusFinal/', 
      },
      {
        id: '',
        common_name: 'african milk tree',
        scientific_name: 'euphorbia trigona ',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/africanMilkTreeFinal/', 
      },
      {
        id: '',
        common_name: 'rattlesnake plant',
        scientific_name: 'goeppertia insignis',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/rattlesnakeFinal/', 
      },
      {
        id: '',
        common_name: 'swiss cheese plant,monstera',
        scientific_name: 'monstera deliciosa,split leaf philodendron',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/monsteraFinal/', 
      },
      {
        id: '',
        common_name: 'fiddle leaf fig',
        scientific_name: 'ficus lyrata',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/fiddleLeafFigFinal/', 
      },
      {
        id: '',
        common_name: 'lucky bamboo',
        scientific_name: 'dracaena sanderiana',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/luckyBambooFinal/', 
      },
      {
        id: '',
        common_name: 'peace lily',
        scientific_name: 'spathiphyllum',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/peaceLilyFinal/', 
      },
      {
        id: '',
        common_name: 'ponytail palm',
        scientific_name: 'beaucarnea recurvata',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/ponytailPalmFinal/', 
      },
      {
        id: '',
        common_name: 'pothos',
        scientific_name: 'epipremnum aureum',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/pothosFinal/', 
      },
      {
        id: '',
        common_name: 'bromeliad',
        scientific_name: 'bromeliaceae',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/bromeliadFinal/', 
      },
      {
        id: '',
        common_name: 'orchid',
        scientific_name: 'orchidaceae',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/orchidFinal/', 
      },
      {
        id: '',
        common_name: 'english ivy',
        scientific_name: 'hedera helix',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/englishIvyFinal/', 
      },
      {
        id: '',
        common_name: "elephant's ear",
        scientific_name: 'alocasia',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/elephantEarsFinal/', 
      },
      {
        id: '',
        common_name: 'prayer plant',
        scientific_name: 'maranta leuconeura',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/prayerPlantFinal/', 
      },
      {
        id: '',
        common_name: 'money tree',
        scientific_name: 'pachira aquatica',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/moneyTreeFinal/', 
      },
      {
        id: '',
        common_name: 'chinese money plant',
        scientific_name: 'pilea peperomioides',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/chineseMoneyFinal/', 
      },
      {
        id: '',
        common_name: 'madagascar palm',
        scientific_name: 'pachypodium lamerei',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/madagascarPalmFinal/', 
      },
      {
        id: '',
        common_name: 'staghorn ferns',
        scientific_name: 'platycerium',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/staghornFernFinal/', 
      },
      {
        id: '',
        common_name: 'zz plant',
        scientific_name: 'zamioculcas',
        url: 'https://herble.s3.us-east-2.amazonaws.com/House+Plants/zzPlantFinal/', 
      },
];

const seedPlants = () => Plant.bulkCreate(plantData)
